name: 'IlPostNews Bot'

on:
  #schedule:
  #  - cron: '* * * * *'  
  workflow_dispatch:
    inputs:
      manual-run:
        description: 'Manual run description'     
        required: true

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt

    - name: Run script
      run: python ilpostnews_bot.py
      env:
        TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
